version: "3"
services:
  go:
    container_name: go_bot
    build:
      context: .
      target: prod
    image: go_bot:prod
    volumes:
      - ./gkey.json:/gkey.json:ro
    env_file:
      - .env
