version: "3"
services:
  go:
    container_name: go_bot
    build:
      context: .
      target: dev
    image: go_bot:dev
    volumes:
      - .:/go/src/johnmerga/locationGrabber:ro
      - /go/src/johnmerga/locationGrabber/.git
    env_file:
      - .env.dev
